export const REGISTER_FIELDS = (formData) => [
  {
    id: 1,
    type: 'text',
    name: 'username',
    label: 'Username',
    placeholder: 'Enter Username',
    pattern: '^[A-Za-z0-9]{3,16}$',
    errorMessage: 'Username should be 3-16 characters long and should not include any special characters!',
    required: true,
  },
  {
    id: 2,
    type: 'email',
    name: 'email',
    label: 'Email',
    placeholder: 'Enter Email',
    errorMessage: 'Please enter a valid email address!',
    required: true,
  },
  {
    id: 3,
    type: 'password',
    name: 'password',
    label: 'Password',
    placeholder: 'Enter Password',
    pattern: '^(?=.*[0-9])(?=.*[a-zA-Z])(?=.*[!@#$%^&*])[a-zA-Z0-9!@#$%^&*]{6,30}$',
    errorMessage: 'Password should be 6-30 characters long and include at least 1 letter, 1 number, 1 special character!',
    required: true,
  },
  {
    id: 4,
    type: 'password',
    name: 'confirmPassword',
    label: 'Confirm Password',
    placeholder: 'Enter Password again',
    pattern: formData.password,
    errorMessage: 'Passwords do not match!',
    required: true,
  },
]

export const LOGIN_FIELDS = (formData) => [
  {
    id: 1,
    type: 'email',
    name: 'email',
    label: 'Email',
    placeholder: 'Enter Email',
    required: true,
  },
  {
    id: 2,
    type: 'password',
    name: 'password',
    label: 'Password',
    placeholder: 'Enter Password',
    required: true,
  },
]

export const SHIPPING_FIELDS = (formData) => [
  {
    id: 1,
    type: 'text',
    name: 'address',
    label: 'Address',
    placeholder: 'Enter Address',
    icon: 'fa fa-address-book',
    required: true,
  },
  {
    id: 2,
    type: 'text',
    name: 'city',
    label: 'City',
    placeholder: 'Enter City',
    icon: 'fa fa-home',
    required: true,
  },
  {
    id: 3,
    type: 'text',
    name: 'postalCode',
    label: 'Postal Code',
    placeholder: 'Enter Postal Code',
    icon: 'fa fa-envelope-open',
    required: true,
  },
  {
    id: 4,
    type: 'text',
    name: 'country',
    label: 'Country',
    placeholder: 'Enter Country',
    icon: 'fa fa-globe',
    required: true,
  },
]

export const PROFILE_FIELDS = (formData) => [
  {
    id: 1,
    type: 'text',
    name: 'username',
    label: 'Username',
    placeholder: 'Enter Username',
    pattern: '^[A-Za-z0-9]{3,16}$',
    errorMessage: 'Username should be 3-16 characters long and should not include any special characters!',
    required: true,
  },
  {
    id: 2,
    type: 'email',
    name: 'email',
    label: 'Email',
    placeholder: 'Enter Email',
    errorMessage: 'Please enter a valid email address!',
    required: true,
  },
  {
    id: 3,
    type: 'password',
    name: 'password',
    label: 'Password',
    placeholder: 'Enter Password',
    pattern: '^(?=.*[0-9])(?=.*[a-zA-Z])(?=.*[!@#$%^&*])[a-zA-Z0-9!@#$%^&*]{6,30}$',
    errorMessage: 'Password should be 6-30 characters long and include at least 1 letter, 1 number, 1 special character!',
    required: true,
  },
  {
    id: 4,
    type: 'password',
    name: 'confirmPassword',
    label: 'Confirm Password',
    placeholder: 'Enter Password again',
    pattern: formData.password,
    errorMessage: 'Passwords do not match!',
    required: true,
  },
]

export const USER_EDIT_FIELDS = (formData) => [
  {
    id: 1,
    type: 'text',
    name: 'username',
    label: 'Username',
    placeholder: 'Enter Username',
    pattern: '^[A-Za-z0-9]{3,16}$',
    errorMessage: 'Username should be 3-16 characters long and should not include any special characters!',
  },
  {
    id: 2,
    type: 'email',
    name: 'email',
    label: 'Email',
    placeholder: 'Enter Email',
    errorMessage: 'Please enter a valid email address!',
  },
  {
    id: 3,
    type: 'checkbox',
    name: 'isAdmin',
    label: 'Is Admin',
    checked: formData.isAdmin,
    parentClass: 'inputWrapper',
  },
]
