export const data = {
  users: [
    {
      _id: 1,
      username: "Plamen",
      password: "123",
      favourites: [],
    },
    {
      _id: 2,
      username: "Test",
      password: "123",
      favourites: [],
    },
  ],
  products: [
    {
      _id: 1,
      brand: "Samsung",
      name: "Samsung Galaxy J6",
      imageUrl: "./images/samsung.jpg",
      OS: "Android 9.0",
      memory: "32GB",
      RAM: "4GB",
      network: "4G",
      SIM: "Dual SIM",
      price: 359.99,
      size: 6.1,
      weight: 157,
      color: "Black",
      release_date: "4 November 2020",
      reviews: [],
    },
    {
      _id: 2,
      brand: "Samsung",
      name: "Samsung Galaxy S10",
      imageUrl: "./images/samsung.jpg",
      OS: "Android 10.0",
      memory: "64GB",
      RAM: "8GB",
      network: "4G",
      SIM: "Dual SIM",
      price: 499.99,
      size: 6.1,
      weight: 157,
      color: "Black",
      release_date: "4 November 2020",
      reviews: [],
    },
  ],
};
